spring:
  jpa:
    show-sql: true
    hibernate:
           ddl-auto: update

  application:
    name: DoctorAuth


  datasource:
     url: jdbc:mysql://172.23.239.228:3306/doctorAuthenDb
     username: root
     password: root
