spring:
 datasource:
   url: jdbc:mysql://172.23.239.228:3306/PatientAuthDBMySQL
   username: root
   password: root
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
   
   
   
   
   
