spring:
 datasource:
   url: jdbc:mysql://172.23.239.234:3306/PatientAuthDB
   username: rootpa
   password: root
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
   
   
   
   
   
